server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/spring-ecommerce
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


jwt:
  secret: MTdCGwG/ZMAngD7j6OMgy8Y+RiAhLQyukw1gmAMU8d0=